[package]
name = "AoC2020"
version = "0.1.0"
authors = ["esposm03 <36164633+esposm03@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
itertools = "0.9.0"
nom = { version = "6.0.1", default-features = false, features = ["alloc"] }
